#!/usr/bin/env bash


cargo test --no-run --message-format=json ${*} \
    | jq -r "select(.profile.test == true) | .executable" \
    | while read bin; do \
        echo "Running valgrind on $bin"; \
        valgrind --leak-check=full --show-leak-kinds=definite,indirect --error-exitcode=1 "$bin"; \
    done
